# Generated by Django 4.0.8 on 2024-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bmaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Cost_per_Unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Durability', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Strength', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Resistance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Performance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Construction_Cost_Over_Time_Years', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Area_Measurements', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Risk_Score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Material_Score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Cost_per_Unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Durability', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Strength', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Resistance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Performance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Construction_Cost_Over_Time_Years', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Area_Measurements', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Risk_Score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Material_Score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='nested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Cost_per_Unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Durability', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Strength', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Resistance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Performance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Construction_Cost_Over_Time_Years', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Area_Measurements', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Risk_Score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Material_Score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
